CREATE TABLE IF NOT EXISTS `savemessage` (
  `CUSID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `IPHONE` int(11) DEFAULT NULL,
  `BINDID` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`CUSID`),
  KEY `FK_Relationship_5` (`CUSID`),
  CONSTRAINT `FK_Relationship_5` FOREIGN KEY (`CUSID`) REFERENCES `customer` (`CUSID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;